import {
  GRINDS,
  SIZES,
  type Category,
  type Product,
  type Variant,
} from "../src/lib/catalog/schema";

export const categories: Category[] = [
  {
    slug: "single-origin",
    name: "Single origin",
    description: "One farm or region per bag, roasted to show off where it grew.",
    position: 1,
  },
  {
    slug: "blends",
    name: "Blends",
    description: "Balanced house blends built for everyday brewing and espresso.",
    position: 2,
  },
  {
    slug: "decaf",
    name: "Decaf",
    description: "All of the flavour, none of the 11pm regret.",
    position: 3,
  },
];

type PriceTable = { "250g": number; "1kg": number };

function variants(price: PriceTable, stock: (size: string, grind: string) => number): Variant[] {
  return SIZES.flatMap((size) =>
    GRINDS.map((grind) => ({
      id: `${size}-${grind}`,
      size,
      grind,
      priceCents: price[size],
      stock: stock(size, grind),
    })),
  );
}

const plenty = () => 40;

export const products: Product[] = [
  {
    slug: "yirgacheffe",
    name: "Yirgacheffe",
    categorySlug: "single-origin",
    origin: "Ethiopia",
    region: "Gedeo Zone",
    process: "Washed",
    roastLevel: 1,
    tastingNotes: ["Jasmine", "Bergamot", "Lemon"],
    description:
      "A floral, tea-like cup from smallholder farmers in southern Ethiopia. Brilliant as a pour-over.",
    bagColor: "#8fa587",
    featured: true,
    active: true,
    variants: variants({ "250g": 1900, "1kg": 6200 }, plenty),
  },
  {
    slug: "huila-pink",
    name: "Huila Pink",
    categorySlug: "single-origin",
    origin: "Colombia",
    region: "Huila",
    process: "Washed",
    roastLevel: 2,
    tastingNotes: ["Raspberry", "Panela", "Rose"],
    description:
      "Pink Bourbon grown at 1,800m. Juicy red fruit up front with a sweet, clean finish.",
    bagColor: "#d98b73",
    featured: true,
    active: true,
    variants: variants({ "250g": 2200, "1kg": 7200 }, (size) => (size === "1kg" ? 6 : 25)),
  },
  {
    slug: "nyeri-aa",
    name: "Nyeri AA",
    categorySlug: "single-origin",
    origin: "Kenya",
    region: "Nyeri",
    process: "Washed",
    roastLevel: 2,
    tastingNotes: ["Blackcurrant", "Grapefruit", "Cane sugar"],
    description: "Bold, winey and bright. The kind of Kenyan that wakes up a milk drink too.",
    bagColor: "#7a3b4a",
    featured: false,
    active: true,
    variants: variants({ "250g": 2100, "1kg": 6800 }, plenty),
  },
  {
    slug: "antigua",
    name: "Antigua",
    categorySlug: "single-origin",
    origin: "Guatemala",
    region: "Antigua",
    process: "Washed",
    roastLevel: 3,
    tastingNotes: ["Milk chocolate", "Almond", "Orange"],
    description: "Grown between three volcanoes. Round, nutty and forgiving on any brewer.",
    bagColor: "#b58a4c",
    featured: false,
    active: true,
    variants: variants({ "250g": 1700, "1kg": 5400 }, plenty),
  },
  {
    slug: "tarrazu-honey",
    name: "Tarrazú Honey",
    categorySlug: "single-origin",
    origin: "Costa Rica",
    region: "Tarrazú",
    process: "Honey",
    roastLevel: 2,
    tastingNotes: ["Apricot", "Honey", "Caramel"],
    description:
      "Dried with some of the fruit still on the bean, giving a syrupy body and stone fruit sweetness.",
    bagColor: "#e0b35a",
    featured: false,
    active: true,
    variants: variants({ "250g": 2000, "1kg": 6400 }, plenty),
  },
  {
    slug: "gayo-highlands",
    name: "Gayo Highlands",
    categorySlug: "single-origin",
    origin: "Indonesia",
    region: "Aceh, Sumatra",
    process: "Wet-hulled",
    roastLevel: 4,
    tastingNotes: ["Cedar", "Dark chocolate", "Clove"],
    description: "Earthy, heavy and low in acidity. A classic Sumatran for French press lovers.",
    bagColor: "#4f5d4a",
    featured: false,
    active: true,
    variants: variants({ "250g": 1800, "1kg": 5800 }, () => 0),
  },
  {
    slug: "sunday-blend",
    name: "Sunday Blend",
    categorySlug: "blends",
    origin: "Brazil & Ethiopia",
    region: "Sul de Minas & Sidama",
    process: "Natural & Washed",
    roastLevel: 3,
    tastingNotes: ["Chocolate", "Red berries", "Caramel"],
    description: "Our house blend. Chocolatey enough for milk, fruity enough to drink black.",
    bagColor: "#3b261b",
    featured: true,
    active: true,
    variants: variants({ "250g": 1500, "1kg": 4800 }, plenty),
  },
  {
    slug: "night-owl",
    name: "Night Owl",
    categorySlug: "blends",
    origin: "Brazil & Sumatra",
    region: "Mogiana & Aceh",
    process: "Natural & Wet-hulled",
    roastLevel: 5,
    tastingNotes: ["Dark chocolate", "Molasses", "Smoke"],
    description: "A dark, syrupy espresso blend that cuts through milk like it means it.",
    bagColor: "#1f2433",
    featured: true,
    active: true,
    variants: variants({ "250g": 1600, "1kg": 5000 }, (size, grind) =>
      size === "1kg" && grind === "espresso" ? 0 : 30,
    ),
  },
  {
    slug: "morning-bloom",
    name: "Morning Bloom",
    categorySlug: "blends",
    origin: "Colombia & Kenya",
    region: "Nariño & Kirinyaga",
    process: "Washed",
    roastLevel: 2,
    tastingNotes: ["Stone fruit", "Citrus", "Brown sugar"],
    description: "Bright and sweet for filter brewing. Named for the bloom in your first pour.",
    bagColor: "#c96f4a",
    featured: false,
    active: true,
    variants: variants({ "250g": 1700, "1kg": 5400 }, plenty),
  },
  {
    slug: "sugarcane-decaf",
    name: "Sugarcane Decaf",
    categorySlug: "decaf",
    origin: "Colombia",
    region: "Caldas",
    process: "Sugarcane EA decaf",
    roastLevel: 3,
    tastingNotes: ["Toffee", "Red apple", "Cocoa"],
    description:
      "Decaffeinated using ethyl acetate made from local sugarcane, so it still tastes like coffee.",
    bagColor: "#9c6b4e",
    featured: false,
    active: true,
    variants: variants({ "250g": 1800, "1kg": 5600 }, plenty),
  },
];
